name: Build Backend

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Clean project
        run: ./mvnw clean

      - name: Compile the project
        run: ./mvnw compile
